@extends('layouts.app')

@section('content')
<div class="flex justify-end mb-4">
    @php ($tw = Vite::asset('resources/css/app.css'))
    <button onclick="printJS({ printable: 'report', type: 'html', css: '{{ $tw }}', ignoreElements: ['.no-print'] })" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Print Report
    </button>
</div>
<div class="p-4" style="position: relative;">
    <img src="{{ asset('assets/gradient.jpg') }}" class="no-print" style="position: fixed; left: 0; z-index: -1; top: 0; width: 100%; height: 100vh; opacity: 0.2; object-fit: cover;" alt="Background">
    <div id="report">
        <h1 class="text-3xl font-bold">Sales Report</h1>
        <p class="mb-6 text-xs text-gray-700">Generated By: {{ Auth::user()->getFullname() }} @ {{ now()->format('M d, Y h:ia') }}</p>

        <div class="grid grid-cols-2 gap-4 mb-6">
            <?php
            $start = request()->query('start', $orders->first() ? $orders->first()->created_at->format('Y-m-d') : 'N/A');
            $end = request()->query('end', $orders->last() ? $orders->last()->created_at->format('Y-m-d') : 'N/A');
            ?>
            <div>
                <h3 class="text-xl font-semibold text-gray-700">Start Date: <span class="text-gray-900">{{ $start }}</span></h3>
            </div>
            <div>
                <h3 class="text-xl font-semibold text-gray-700">End Date: <span class="text-gray-900">{{ $end }}</span></h3>
            </div>
        </div>

        <div class="grid grid-cols-3 gap-4 mb-6">
            <?php
            $goodsSold = 0;
            $netRevenue = 0;
            $netProfit = 0;

            foreach ($orders as $order) {
                foreach ($order->getItemsAndQuantity() as [$id, $qty]) {
                    $goodsSold += $qty;
                    $netRevenue += $order->getTotal();
                    $netProfit += $order->getProfit();
                }
            }
            ?>

            <div>
                <h3 class="text-xl font-semibold">Goods Sold: {{ number_format($goodsSold, 0) }}</h3>
            </div>
            <div>
                <h3 class="text-xl font-semibold">Net Revenue: {{ number_format($netRevenue, 2) }} PHP</h3>
            </div>
            <div>
                <h3 class="text-xl font-semibold">Net Profit: {{ number_format($netProfit, 2) }} PHP</h3>
            </div>
        </div>

        <table class="min-w-full bg-white border border-gray-200">
            <thead>
                <tr class="bg-gray-100">
                    <th class="py-2 px-4 border-b" title="Order ID">#</th>
                    <th class="py-2 px-4 border-b">Product</th>
                    <th class="py-2 px-4 border-b">Quantity</th>
                    <th class="py-2 px-4 border-b">Total Price</th>
                    <th class="py-2 px-4 border-b">Order Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orders as $order)
                @foreach ($order->getItemsAndQuantity() as [$id, $qty])
                @php($product = App\Models\Product::find($id))
                <tr>
                    <td class="py-2 px-4 border-b">{{ $order->id }}</td>
                    <td class="py-2 px-4 border-b">{{ $product->name }}</td>
                    <td class="py-2 px-4 border-b">{{ $qty }}</td>
                    <td class="py-2 px-4 border-b">{{ number_format($product->price * $qty, 2) }} PHP</td>
                    <td class="py-2 px-4 border-b">{{ $order->created_at->format('M d, Y h:ia') }}</td>
                </tr>
                @endforeach
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection