@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4 py-6">
    <div class="flex justify-end mb-6">
        @php ($tw = Vite::asset('resources/css/app.css'))
        <button onclick="printJS({ printable: 'report', type: 'html', css: '{{ $tw }}', ignoreElements: ['.no-print'] })" class="bg-blue-600 hover:bg-blue-700 text-white font-medium py-2 px-6 rounded-md shadow transition duration-150 ease-in-out flex items-center">
            <i class="fas fa-print mr-2"></i>Export Report
        </button>
    </div>
    
    <div class="bg-white shadow-xl rounded-lg border border-gray-100">
        <div id="report" class="p-8">
            <div class="text-center mb-10 pb-6 border-b border-gray-200">
                <h1 class="text-4xl font-bold text-gray-800 mb-2">Sales Performance Report</h1>
                <p class="text-gray-600">Generated By: {{ Auth::user()->getFullname() }} | {{ now()->format('F d, Y h:i A') }}</p>
            </div>

            <?php
            $start = request()->query('start', $orders->first() ? $orders->first()->created_at->format('Y-m-d') : 'N/A');
            $end = request()->query('end', $orders->last() ? $orders->last()->created_at->format('Y-m-d') : 'N/A');
            
            $goodsSold = 0;
            $netRevenue = 0;
            $netProfit = 0;

            foreach ($orders as $order) {
                foreach ($order->getItemsAndQuantity() as [$id, $qty]) {
                    $goodsSold += $qty;
                    $netRevenue += $order->getTotal();
                    $netProfit += $order->getProfit();
                }
            }
            ?>

            <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-10">
                <div class="md:col-span-1 bg-blue-50 rounded-lg p-6 shadow-sm">
                    <h3 class="text-lg font-semibold text-gray-700 mb-4 border-b pb-2 border-blue-100">Report Period</h3>
                    <div class="flex justify-between items-center mb-2">
                        <span class="text-gray-600">From:</span>
                        <span class="font-medium text-gray-800">{{ \Carbon\Carbon::parse($start)->format('F d, Y') }}</span>
                    </div>
                    <div class="flex justify-between items-center">
                        <span class="text-gray-600">To:</span>
                        <span class="font-medium text-gray-800">{{ \Carbon\Carbon::parse($end)->format('F d, Y') }}</span>
                    </div>
                </div>
                
                <div class="md:col-span-3 grid grid-cols-3 gap-4">
                    <div class="text-center p-6 bg-blue-50 rounded-lg shadow-sm border-t-4 border-blue-500">
                        <div class="text-3xl font-bold text-blue-600 mb-2">{{ number_format($goodsSold, 0) }}</div>
                        <div class="text-sm font-medium text-gray-600">Total Items Sold</div>
                    </div>
                    <div class="text-center p-6 bg-green-50 rounded-lg shadow-sm border-t-4 border-green-500">
                        <div class="text-3xl font-bold text-green-600 mb-2">₱{{ number_format($netRevenue, 2) }}</div>
                        <div class="text-sm font-medium text-gray-600">Total Revenue</div>
                    </div>
                    <div class="text-center p-6 bg-purple-50 rounded-lg shadow-sm border-t-4 border-purple-500">
                        <div class="text-3xl font-bold text-purple-600 mb-2">₱{{ number_format($netProfit, 2) }}</div>
                        <div class="text-sm font-medium text-gray-600">Net Profit</div>
                    </div>
                </div>
            </div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8 mb-10">
                <div class="bg-gray-50 p-6 rounded-lg shadow-sm">
                    <h3 class="text-lg font-semibold text-gray-700 mb-4 pb-2 border-b border-gray-200">
                        <i class="fas fa-chart-line mr-2 text-blue-500"></i>Top 3 Products
                    </h3>
                    <?php
                    $productCounts = [];
                    foreach ($orders as $order) {
                        foreach ($order->getItemsAndQuantity() as [$id, $qty]) {
                            if (!isset($productCounts[$id])) {
                                $productCounts[$id] = 0;
                            }
                            $productCounts[$id] += $qty;
                        }
                    }
                    arsort($productCounts);
                    $topProducts = array_slice($productCounts, 0, 3, true);
                    ?>
                    @foreach($topProducts as $productId => $quantity)
                        @php($product = App\Models\Product::find($productId))
                        <div class="flex items-center justify-between mb-4 p-3 bg-white rounded shadow-sm">
                            <div>
                                <div class="font-semibold text-gray-800">{{ $product->name }}</div>
                                <div class="text-sm text-gray-600">{{ number_format($quantity) }} units</div>
                            </div>
                            <div class="text-blue-500 font-bold text-lg">
                                #{{ $loop->iteration }}
                            </div>
                        </div>
                    @endforeach
                </div>

                <div class="bg-gray-50 p-6 rounded-lg shadow-sm">
                    <h3 class="text-lg font-semibold text-gray-700 mb-4 pb-2 border-b border-gray-200">
                        <i class="fas fa-users mr-2 text-green-500"></i>Top 3 Customers
                    </h3>
                    <?php
                    $customerTotals = [];
                    foreach ($orders as $order) {
                        if (!isset($customerTotals[$order->client_name])) {
                            $customerTotals[$order->client_name] = 0;
                        }
                        $customerTotals[$order->client_name] += $order->getTotal();
                    }
                    arsort($customerTotals);
                    $topCustomers = array_slice($customerTotals, 0, 3, true);
                    ?>
                    @foreach($topCustomers as $customerName => $total)
                        <div class="flex items-center justify-between mb-4 p-3 bg-white rounded shadow-sm">
                            <div>
                                <div class="font-semibold text-gray-800">{{ $customerName }}</div>
                                <div class="text-sm text-gray-600">₱{{ number_format($total, 2) }}</div>
                            </div>
                            <div class="text-green-500 font-bold text-lg">
                                #{{ $loop->iteration }}
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>

            <div class="mb-6">
                <h3 class="text-lg font-semibold text-gray-700 mb-4 pb-2 border-b border-gray-200">
                    <i class="fas fa-list-alt mr-2 text-indigo-500"></i>Detailed Transaction History
                </h3>
                <div class="overflow-x-auto shadow-sm rounded-lg">
                    <table class="min-w-full bg-white border border-gray-200">
                        <thead>
                            <tr class="bg-gray-100">
                                <th class="py-3 px-4 border-b font-semibold text-gray-700 text-left">#</th>
                                <th class="py-3 px-4 border-b font-semibold text-gray-700 text-left">Product</th>
                                <th class="py-3 px-4 border-b font-semibold text-gray-700 text-center">Quantity</th>
                                <th class="py-3 px-4 border-b font-semibold text-gray-700 text-right">Total Price</th>
                                <th class="py-3 px-4 border-b font-semibold text-gray-700 text-right">Order Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($orders as $order)
                                @foreach ($order->getItemsAndQuantity() as [$id, $qty])
                                    @php($product = App\Models\Product::find($id))
                                    <tr class="hover:bg-gray-50 border-b border-gray-100">
                                        <td class="py-3 px-4 text-gray-600">{{ $order->id }}</td>
                                        <td class="py-3 px-4 font-medium text-gray-800">{{ $product->name }}</td>
                                        <td class="py-3 px-4 text-center">{{ $qty }}</td>
                                        <td class="py-3 px-4 text-right font-medium">₱{{ number_format($product->price * $qty, 2) }}</td>
                                        <td class="py-3 px-4 text-right text-gray-600">{{ $order->created_at->format('M d, Y h:i A') }}</td>
                                    </tr>
                                @endforeach
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div class="text-center text-gray-500 text-sm mt-10 pt-4 border-t border-gray-200">
                This is an official report generated from the Warehouse Management System.<br>
                © {{ date('Y') }} All Rights Reserved.
            </div>
        </div>
    </div>
</div>
@endsection