@extends('layouts.app')

@section('content')
<div class="flex justify-end mb-4">
    @php ($tw = Vite::asset('resources/css/app.css'))
    <button onclick="printJS({ printable: 'report', type: 'html', css: '{{ $tw }}', ignoreElements: ['.no-print'] })" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        <i class="fas fa-print mr-2"></i>Print Report
    </button>
</div>
<div class="p-6 bg-white shadow-lg rounded-lg">
    <div id="report">
        <div class="text-center mb-8">
            <h1 class="text-4xl font-bold text-gray-800">Sales Report</h1>
            <p class="text-sm text-gray-600 mt-2">Generated By: {{ Auth::user()->getFullname() }} | {{ now()->format('F d, Y h:i A') }}</p>
        </div>

        <div class="grid grid-cols-2 gap-6 mb-8 bg-gray-50 p-6 rounded-lg">
            <?php
            $start = request()->query('start', $orders->first() ? $orders->first()->created_at->format('Y-m-d') : 'N/A');
            $end = request()->query('end', $orders->last() ? $orders->last()->created_at->format('Y-m-d') : 'N/A');
            ?>
            <div class="border-r border-gray-300">
                <h3 class="text-lg font-semibold text-gray-600">Report Period</h3>
                <div class="mt-2">
                    <span class="text-gray-600">From:</span> <span class="font-medium">{{ \Carbon\Carbon::parse($start)->format('F d, Y') }}</span>
                </div>
                <div class="mt-1">
                    <span class="text-gray-600">To:</span> <span class="font-medium">{{ \Carbon\Carbon::parse($end)->format('F d, Y') }}</span>
                </div>
            </div>
            
            <?php
            $goodsSold = 0;
            $netRevenue = 0;
            $netProfit = 0;

            foreach ($orders as $order) {
                foreach ($order->getItemsAndQuantity() as [$id, $qty]) {
                    $goodsSold += $qty;
                    $netRevenue += $order->getTotal();
                    $netProfit += $order->getProfit();
                }
            }
            ?>
            <div>
                <h3 class="text-lg font-semibold text-gray-600">Summary</h3>
                <div class="grid grid-cols-3 gap-4 mt-2">
                    <div class="text-center p-2 bg-blue-50 rounded">
                        <div class="text-sm text-gray-600">Total Items</div>
                        <div class="font-bold text-blue-600">{{ number_format($goodsSold, 0) }}</div>
                    </div>
                    <div class="text-center p-2 bg-green-50 rounded">
                        <div class="text-sm text-gray-600">Revenue</div>
                        <div class="font-bold text-green-600">₱{{ number_format($netRevenue, 2) }}</div>
                    </div>
                    <div class="text-center p-2 bg-purple-50 rounded">
                        <div class="text-sm text-gray-600">Profit</div>
                        <div class="font-bold text-purple-600">₱{{ number_format($netProfit, 2) }}</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mb-8 bg-gray-50 p-6 rounded-lg">
            <h3 class="text-lg font-semibold text-gray-600 mb-4">Top 3 Most Popular Products</h3>
            <?php
            $productCounts = [];
            foreach ($orders as $order) {
                foreach ($order->getItemsAndQuantity() as [$id, $qty]) {
                    if (!isset($productCounts[$id])) {
                        $productCounts[$id] = 0;
                    }
                    $productCounts[$id] += $qty;
                }
            }
            arsort($productCounts);
            $topProducts = array_slice($productCounts, 0, 3, true);
            ?>
            <div class="grid grid-cols-3 gap-4">
                @foreach($topProducts as $productId => $quantity)
                    @php($product = App\Models\Product::find($productId))
                    <div class="text-center p-4 bg-white rounded shadow">
                        <div class="font-semibold text-gray-800">{{ $product->name }}</div>
                        <div class="text-sm text-gray-600 mt-1">Sold: {{ number_format($quantity) }} units</div>
                    </div>
                @endforeach
            </div>
        </div>

        <div class="mb-8 bg-gray-50 p-6 rounded-lg">
            <h3 class="text-lg font-semibold text-gray-600 mb-4">Top 3 Customers</h3>
            <?php
            $customerTotals = [];
            foreach ($orders as $order) {
                if (!isset($customerTotals[$order->client_name])) {
                    $customerTotals[$order->client_name] = 0;
                }
                $customerTotals[$order->client_name] += $order->getTotal();
            }
            arsort($customerTotals);
            $topCustomers = array_slice($customerTotals, 0, 3, true);
            ?>
            <div class="grid grid-cols-3 gap-4">
                @foreach($topCustomers as $customerName => $total)
                    <div class="text-center p-4 bg-white rounded shadow">
                        <div class="font-semibold text-gray-800">{{ $customerName }}</div>
                        <div class="text-sm text-gray-600 mt-1">Total: ₱{{ number_format($total, 2) }}</div>
                    </div>
                @endforeach
            </div>
        </div>

        <div class="overflow-x-auto">
            <table class="min-w-full bg-white border border-gray-200 rounded-lg">
                <thead>
                    <tr class="bg-gray-50">
                        <th class="py-3 px-4 border-b font-semibold text-gray-600 text-left">#</th>
                        <th class="py-3 px-4 border-b font-semibold text-gray-600 text-left">Product</th>
                        <th class="py-3 px-4 border-b font-semibold text-gray-600 text-center">Quantity</th>
                        <th class="py-3 px-4 border-b font-semibold text-gray-600 text-right">Total Price</th>
                        <th class="py-3 px-4 border-b font-semibold text-gray-600 text-right">Order Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($orders as $order)
                        @foreach ($order->getItemsAndQuantity() as [$id, $qty])
                            @php($product = App\Models\Product::find($id))
                            <tr class="hover:bg-gray-50">
                                <td class="py-3 px-4 border-b text-gray-600">{{ $order->id }}</td>
                                <td class="py-3 px-4 border-b">{{ $product->name }}</td>
                                <td class="py-3 px-4 border-b text-center">{{ $qty }}</td>
                                <td class="py-3 px-4 border-b text-right">₱{{ number_format($product->price * $qty, 2) }}</td>
                                <td class="py-3 px-4 border-b text-right text-gray-600">{{ $order->created_at->format('M d, Y h:i A') }}</td>
                            </tr>
                        @endforeach
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection